name: Build ZMK firmware
on: [pull_request, workflow_dispatch]
#[push, pull_request, workflow_dispatch]
jobs:
  build:
    name: "typeractive.${{ github.run_number }}"
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
